# Basic Information 
title:  Guhan Zheng
position: Senior Research Associate
department: School of Computing and Communications
department_link: https://www.lancaster.ac.uk/scc/
affiliation: Lancaster University
affiliation_link: https://www.lancaster.ac.uk/
affiliation_logo: ./assets/img/uni.png


# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
#email: g.zheng2@lancaster.ac.uk
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=377WJ7IAAAAJ&hl=EN
linkedin: https://www.linkedin.com/in/guhan-zheng-69139a184/
ieee: https://ieeexplore.ieee.org/author/37089447351

# Images 
avatar: ./assets/img/guhan2.jpg  
#favicon: ./assets/img/nju_favicon.ico
#favicon_dark: ./assets/img/nju_favicon.ico


# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
